# Generated by Django 4.1.2 on 2022-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_restorelinkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='{"boards":[{"name":"Untitled Board","id":"b0","settings":{"theme":null},"cards":[],"identifier":0}],"settings":{"userName":"User","dataPersistence":true},"currentBoard":0,"identifier":1}')),
            ],
        ),
    ]
