# Generated by Django 4.1.2 on 2022-12-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='boards',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.boards'),
        ),
    ]
